### ISSUE TITLE
Research about Swagger UI improvement

### ISSUE THREAD

**Issue by roaminro** [roaminro/koinos-rest#19]
See if the Swagger page can be customized with a "nicer" look.

**Comment by gtandes** [comment]
According to my current knowledge, Docusaurus seems to be built for React and not Nextjs.

https://stackoverflow.com/questions/72544932/how-to-add-a-docusaurus-website-within-next-js-website-as-a-route

Known documentation library for Nextjs is Nextra

https://nextra.site/docs/guide

but not certain whether it supports Swagger out of the box.

Currently, dev recommends just doing a custom FE.
