### ISSUE TITLE
Prepare transaction endpoint

### ISSUE THREAD

**Issue by roaminro** [roaminro/koinos-rest#5]
Add a "prepare" endpoint to the "transaction" routes group.

- POST endpoint:
 - receive a transaction as `TransactionJson` 
 - create a koilib `Signer` as follow `const signer = Signer.FromSeed('dummy_signer')`
 - use the `signer` and call `prepareTransaction` with the transaction passed to the endpoint
 - return the result from `prepareTransaction` to the user

This endpoint takes a "non-prepared" transaction and returns a "prepared" transaction.
Elements of a transaction that can be "prepared" are:
- transaction id
- chain id
- rc limit ( if "payer" field provided)
- nonce (if "payer" field provided)
- operation merkle root
- encode operation if needed

Example input:
```json
{
  "header": {
    "payer": "1PWdJ3VFB6kwu6wLdLPr9BwQZrNiPs7g8j"
  },
  "operations": [
    {
      "call_contract": {
        "contract_id": "Rf8gGKq42QBxS3M",
        "entry_point": 12,
        "args": "YXJncw=="
      }
    }
  ]
}
```

output:

```json
{
  "header": {
    "chain_id": "EiBZK_GGVP0H_fXVAM3j6EAuz3-B-l3ejxRSewi7qIBfSA==",
    "rc_limit": "1304100001",
    "nonce": "KAw=",
    "operation_merkle_root": "EiDekOnwdGY6TbwkpU_WXFd8_hCFu8cnJO4hwTaAEcFekg==",
    "payer": "1PWdJ3VFB6kwu6wLdLPr9BwQZrNiPs7g8j"
  },
  "operations": [
    {
      "call_contract": {
        "contract_id": "Rf8gGKq42QBxS3M",
        "entry_point": 12,
        "args": "YXJncw=="
      }
    }
  ],
  "id": "0x12205658bb74ecff86f6edb9e8bf73b26a8c2f0f077a98cd067caf5ae6a90fb088be"
}
```

**Comment by gtandes** [comment]
- signer.prepareTransaction() is now deprecated. It is now utilized by calling on Transaction.prepareTransaction(), where Transaction is imported from koilib

**Comment by gtandes** [comment]
Note: Transaction.prepareTransaction()

already prepares the ff elements under the hood:

transaction id
chain id
rc limit ( if "payer" field provided)
nonce (if "payer" field provided)
operation merkle root
encode operation if needed
