### ISSUE TITLE
Add endpoint to retrieve the owner of a Nickname

### ISSUE THREAD

**Issue by roaminro** [roaminro/koinos-rest#9]
`Nicknames` is another nameservice on Koinos. We'd like to add a similar endpoint to `/api/kap/{name}/address` where a name is passed and the owner of that name is returned.

Example: 
`/api/nicknames/@jga/address` should return `1MdqwaSBy6rbasPJ9vmg2pZFJSVZ29GFpZ`

Abi for the Nicknames contract:
[nicknames.json](https://github.com/roaminro/koinos-rest/files/13232950/nicknames.json)

- Nicknames contract id: `1KD9Es7LBBjA1FY3ViCgQJ7e6WH1ipKbhz`
- Entry point:  `owner_of `
- params:` { "token_id": ... }` where `token_id`  is the name encoded in hexadecimal

To encode a name into an hexadecimal value, create the following helper:

```ts
import { utils } from 'koilib'

function stringToHex(str: string): string {
      return `0x${utils.toHexString(new TextEncoder().encode(str))}`
    }
```

Function to get the owner:
```ts
const { result } = await contract.functions.owner_of<{ account: string }>({
    token_id: <YOUR_TOKEN_ID>
  })
```

Get inspiration from the KAP service that already exsits at https://github.com/roaminro/koinos-rest/blob/main/services/kap.ts

**Comment by gtandes** [comment]
Hi ser Roamin. Can we have example input/output for this?

**Comment by roaminro** [comment]
I'm not sure what you mean, there is already an example in the issue ;)

> Example:
/api/nicknames/jga/address should return 1MdqwaSBy6rbasPJ9vmg2pZFJSVZ29GFpZ
